import React from 'react'
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import "../components/Form.css";
import "../App.css";
import { useEffect, useState } from "react";
import axios from "axios";
import { useNavigate } from 'react-router-dom';
import { host } from "../components/variables";

function Course() {
    const [uj_faculty1, setUj_faculty1] = useState("");
    const [uj_faculty2, setUj_faculty2] = useState("");
    const [uj_course1, setUj_course1] = useState("");
    const [uj_course2, setUj_course2] = useState("");
    
    const [uwc_faculty1, setUwc_faculty1] = useState("");
    const [uwc_faculty2, setUwc_faculty2] = useState("");
    const [uwc_course1, setUwc_course1] = useState("");
    const [uwc_course2, setUwc_course2] = useState("");
    
    const [nwu_campus1, setNwu_campus1] = useState("");
    const [nwu_campus2, setNwu_campus2] = useState("");
    const [nwu_course1, setNwu_course1] = useState("");
    const [nwu_course2, setNwu_course2] = useState("");

    const handleSubmit = (e) => {
        e.preventDefault();
        const data = {
            uj_faculty1,
            uj_faculty2,
            uj_course1,
            uj_course2,
            uwc_faculty1,
            uwc_faculty2,
            uwc_course1,
            uwc_course2,
            nwu_campus1,
            nwu_campus2,
            nwu_course1,
            nwu_course2,
            "id": localStorage.getItem("userId")
        };
        axios.post(host+"/api/updateCourse", data).then((res) => {
            console.log(res);
        });

        navigate("/application/files");
    }

    const navigate = useNavigate();

    useEffect(() => {
        document.title = "Course Selection";

        if (localStorage.getItem("userId") === null){
            navigate("/login");
        }

    }, []);

    function uj1(faculty, course){
        const arts = {'B8FD1Q': 'BA IN FASHION DESIGN', 'B8BA6Q': 'BA IN INTERIOR DESIGN', 'B8BA7Q': 'BA IN VISUAL ART', 'B8CD2Q': 'BA in Design in Communication Design', 'B8DM3Q': 'BA in Digital Media Design', 'B8ID1Q': 'BA in Industrial Design', 'B8BA3Q': 'Bachelor of Architecture', 'D8JD1Q': 'DIPLOMA IN JEWELLERY DESIGN & MANUFACTURE', 'D8AT1Q': 'Diploma in Architecture', 'D8FP1Q': 'Diploma in Fashion Production'};
        const collegeBusines = {'B34PKQ': 'BA (PUBLIC MANAGEMENT AND GOVERNANCE) - APK', 'B34PSQ': 'BA (PUBLIC MANAGEMENT AND GOVERNANCE) - SWC', 'B3AE7Q': 'BACHELOR OF COMMERCE IN ACCOUNTING EXTENDED', 'B3F17Q': 'BACHELOR OF COMMERCE IN FINANCE', 'B3FE7Q': 'BACHELOR OF COMMERCE IN FINANCE EXTENDED', 'B34HOQ': 'BACHELOR OF HOSPITALITY MANAGEMENT', 'B34HRQ': 'BACHELOR OF HUMAN RESOURCE MANAGEMENT', 'B34TOQ': 'BACHELOR OF TOURISM DEVELOPMENT & MANAGEMENT', 'B34BEQ': 'BCOM IN BUSINESS MANAGEMENT EXTENDED', 'B1CISQ': 'BCOM IN INFORMATION SYSTEMS', 'B1CMMQ': 'BCOM IN MARKETING MANAGEMENT', 'B34TLQ': 'BCOM IN TRANSPORT & LOGISTICS MANAGEMENT', 'B34IMQ': 'BCom IN INFORMATION MANAGEMENT', 'B34BMQ': 'BCom in Business Management', 'B3N14Q': 'BCom in Economics and Econometrics', 'B3NE4Q': 'BCom in Economics and Econometrics Ext', 'B1CEMQ': 'BCom in Entrepreneurial Management', 'B34IPQ': 'BCom in Industrial Psychology', 'BCA012': 'Bachelor of Accounting', 'B3A17Q': 'Bachelor of Commerce in Accounting', 'D34P2Q': 'DIP IN PEOPLE MANAGEMENT', 'D34PEQ': 'DIP IN PEOPLE MANAGEMENT (EXTENDED)', 'D1TRMQ': 'DIP TRANSPORTATION MANAGEMENT', 'D1MKTQ': 'DIP: MARKETING', 'D1RBMQ': 'DIP: RETAIL BUSINESS MANAGEMENT', 'D1SBMQ': 'DIP: SMALL BUSINESS MANAGEMENT', 'D1SBME': 'DIP: SMALL BUSINESS MANAGEMENT (EXTENDED)', 'D1TRME': 'DIP: TRANSPORTATION MANAGEMENT', 'DI1401': 'DIPLOMA IN BUSINESS INFORMATION TECHNOLOGY', 'D1LOGQ': 'DIPLOMA IN LOGISTICS', 'D1LOGE': 'DIPLOMA IN LOGISTICS EXTENDED', 'D34TMQ': 'DIPLOMA IN TOURISM MANAGEMENT', 'D3A15Q': 'Diploma in Accountancy', 'D34F9Q': 'Diploma in Financial Services Operations', 'D34FBQ': 'Diploma in Food and Beverage Operations'};
        const education = {'B5BFPQ': 'BED FOUNDATION PHASE TEACHING (GRADES R-3)', 'B5BITQ': 'BED INTERMEDIATE PHASE TEACHING (GRADES 4-7)', 'B5LOPQ': 'BED SENIOR PHASE &  FET TEACHING (PSYCHOLOGY)', 'B5BSAQ': 'BED SENIOR PHASE & FET TEACHING (ACCOUNTING)', 'B5LAFQ': 'BED SENIOR PHASE & FET TEACHING (AFRIKAANS)', 'B5BSEQ': 'BED SENIOR PHASE & FET TEACHING (ECONOMICS)', 'B5LAEQ': 'BED SENIOR PHASE & FET TEACHING (ENGLISH)', 'B5SGEQ': 'BED SENIOR PHASE & FET TEACHING (GEOGRAPHY)', 'B5LAZQ': 'BED SENIOR PHASE & FET TEACHING (ISIZULU)', 'B5SMMQ': 'BED SENIOR PHASE & FET TEACHING (MATHEMATICS)', 'B5LASQ': 'BED SENIOR PHASE & FET TEACHING (SEPEDI)', 'B5BSBQ': 'BED SENIOR PHASE & FET TEACHING: BUSINESS MGT', 'B5SLSQ': 'BED SENIOR PHASE & FET TEACHING: LIFE SCIENCE', 'B5SPSQ': 'BED SENIOR PHASE & FET TEACHING: PHYS SCIENCE'};
        const engineering  = {'B6CISQ': 'B ENG IN CIVIL ENGINEERING', 'B6CE1Q': 'B ENG TECH IN CHEMICAL ENGINEERING', 'B6CV3Q': 'B ENG TECH IN CIVIL ENGINEERING', 'B6CX3Q': 'B ENG TECH IN CIVIL ENGINEERING EXTENDED', 'B6EL1Q': 'B ENG TECH IN ELECTRICAL ENGINEERING', 'B6L1XQ': 'B ENG TECH IN ELECTRICAL ENGINEERING EXTENDED', 'B6EXTQ': 'B ENG TECH IN EXTRACTION METALLURGY', 'B6EX0Q': 'B ENG TECH IN EXTRACTION METALLURGY EXTENDED', 'B6MINQ': 'B ENG TECH IN MINING ENGINEERING', 'B6CN0Q': 'BACHELOR OF CONSTRUCTION', 'B6SC0Q': 'BACHELOR OF CONSTRUCTION (EXTENDED)', 'B6SU0Q': 'BACHELOR OF MINE SURVEYING', 'B6IN2Q': 'BENG TECH IN INDUSTRIAL ENGINEERING', 'B6IX2Q': 'BENG TECH IN INDUSTRIAL ENGINEERING EXTENDED', 'B6MC2Q': 'BENG TECH IN MECHANICAL ENGINEERING', 'B6MX2Q': 'BENG TECH IN MECHANICAL ENGINEERING EXTENDED', 'B6PY2Q': 'BENG TECH IN PHYSICAL METALLURGY', 'B6PX2Q': 'BENG TECH IN PHYSICAL METALLURGY EXTENDED', 'B6ELSQ': 'BING IN ELECTRICAL & ELECTRONIC ENGINEERING', 'B6MESQ': 'BING IN MECHANICAL ENGINEERING', 'B6UP0Q': 'Bachelors of Urban and Regional Planning', 'D6MASQ': 'DIPLOMA MANAGEMENT SERVICES', 'D6MAEQ': 'DIPLOMA MANAGEMENT SERVICES (EXT)', 'D6OPMQ': 'DIPLOMA OPERATIONS MANAGEMENT', 'D6OPEQ': 'DIPLOMA OPERATIONS MANAGEMENT EXTENDED'};
        const science = {'B2I02Q': 'BSC COMPUTER SCIENCE & INFORMATICS', 'B2I04Q': 'BSC COMPUTER SCIENCE & INFORMATICS AI', 'B2E01Q': 'BSC COMPUTER SCIENCE & INFORMATICS EXT', 'B2L10Q': 'BSC LIFE & ENV (BIOCHEM AND BOTANY)', 'B2E10Q': 'BSC LIFE & ENV (BIOCHEM AND BOTANY) EXT', 'B2L11Q': 'BSC LIFE & ENV (BOTANY AND CHEM)', 'B2E11Q': 'BSC LIFE & ENV (BOTANY AND CHEM) EXT', 'B2L12Q': 'BSC LIFE & ENV (BOTANY AND ZOOLOGY)', 'B2E12Q': 'BSC LIFE & ENV (BOTANY AND ZOOLOGY) EXT', 'B2L20Q': 'BSC LIFE & ENV (GEOG AND ENVIRO MGT)', 'B2E13Q': 'BSC LIFE & ENV (GEOG AND ENVIRO MGT) EXT', 'B2L25Q': 'BSC LIFE & ENV (GEOLOGY & GEOG)', 'B2L24Q': 'BSC LIFE & ENV (GEOLOGY AND ENVIRO MGT)', 'B2L18Q': 'BSC LIFE & ENV (PHYSIOLOGY & BIOCHEM)', 'B2E14Q': 'BSC LIFE & ENV (PHYSIOLOGY & BIOCHEM) EXT', 'B2L19Q': 'BSC LIFE & ENV (PHYSIOLOGY & PSYCHOLOGY)', 'B2E15Q': 'BSC LIFE & ENV (PHYSIOLOGY & PSYCHOLOGY) EXT', 'B2L13Q': 'BSC LIFE & ENV (ZOOLOGY AND BIOCHEM)', 'B2E17Q': 'BSC LIFE & ENV (ZOOLOGY AND BIOCHEM) EXT', 'B2L14Q': 'BSC LIFE & ENV (ZOOLOGY AND CHEM)', 'B2E18Q': 'BSC LIFE & ENV (ZOOLOGY AND CHEM) EXT', 'B2L15Q': 'BSC LIFE & ENV (ZOOLOGY AND ENVIRO MGT)', 'B2E19Q': 'BSC LIFE & ENV (ZOOLOGY AND ENVIRO MGT) EXT', 'B2L16Q': 'BSC LIFE & ENV (ZOOLOGY AND GEOG)', 'B2E20Q': 'BSC LIFE & ENV (ZOOLOGY AND GEOG) EXT', 'B2M52Q': 'BSC MATH (ACTUARIAL SCIENCE)', 'B2M40Q': 'BSC MATH (APPLIED MATHS AND COMP SCIENCE)', 'B2M42Q': 'BSC MATH (APPLIED MATHS AND MATHS)', 'B2M41Q': 'BSC MATH (APPLIED MATHS AND STATS)', 'B2M43Q': 'BSC MATH (COMPUTATIONAL SCIENCE)', 'B2M45Q': 'BSC MATH (MATHS AND COMP SCIENCE)', 'B2M51Q': 'BSC MATH (MATHS AND ECON - FIN ORIENT)', 'B2M46Q': 'BSC MATH (MATHS AND INFORMATICS)', 'B2M48Q': 'BSC MATH (MATHS AND PSYCHOLOGY)', 'B2M49Q': 'BSC MATH (MATHS AND STATS - FIN ORIENT)', 'B2M47Q': 'BSC MATH (MATHS AND STATS)', 'B2M44Q': 'BSC MATH (STATS AND COMP SCIENCE)', 'B2M50Q': 'BSC MATH (STATS AND ECONOMICS - FIN ORIENT)', 'B2E40Q': 'BSC MATHS (APPLIED MATHS AND COMP SC) EXT', 'B2E42Q': 'BSC MATHS (APPLIED MATHS AND MATHS) EXT', 'B2E41Q': 'BSC MATHS (APPLIED MATHS AND STATS) EXT', 'B2E44Q': 'BSC MATHS (MATHS AND COMP SC) EXT', 'B2E45Q': 'BSC MATHS (MATHS AND INFORMATICS) EXT', 'B2E47Q': 'BSC MATHS (MATHS AND PSYCHOLOGY) EXT', 'B2E46Q': 'BSC MATHS (MATHS AND STATS) EXT', 'B2E43Q': 'BSC MATHS (STATS AND COMP SCIENCE) EXT', 'B2P70Q': 'BSC PHYSICS (BIOCHEM AND CHEM)', 'B2E70Q': 'BSC PHYSICS (BIOCHEM AND CHEM) EXT', 'B2P71Q': 'BSC PHYSICS (CHEM AND MATHS)', 'B2E71Q': 'BSC PHYSICS (CHEM AND MATHS) EXT', 'B2P72Q': 'BSC PHYSICS (CHEM AND PHYSICS)', 'B2E72Q': 'BSC PHYSICS (CHEM AND PHYSICS) EXT', 'B2P81Q': 'BSC PHYSICS (GEOLOGY AND CHEM)', 'B2P82Q': 'BSC PHYSICS (GEOLOGY AND MATHS)', 'B2P83Q': 'BSC PHYSICS (GEOLOGY AND PHYSICS)', 'B2P77Q': 'BSC PHYSICS (PHYSICS AND APPLIED MATHS)', 'B2E73Q': 'BSC PHYSICS (PHYSICS AND APPLIED MATHS) EXT', 'B2P78Q': 'BSC PHYSICS (PHYSICS AND MATHS)', 'B2E74Q': 'BSC PHYSICS (PHYSICS AND MATHS) EXT', 'B2I01Q': 'Bachelor of Science in Information Tech', 'D2ACXQ': 'Diploma in Analytical Chemistry (ext)', 'D2BTEQ': 'Diploma in Biotechnology (EXT)', 'D2FTEQ': 'Diploma in Food Technology (EXT)'};
        const health = {'B9M04Q': 'B OF RADIATION THERAPY', 'B9O02Q': 'B in Optometry', 'B9M01Q': 'B of Diagnostic Radiography', 'B9M03Q': 'B of Diagnostic Ultrasound', 'B9M02Q': 'B of Nuclear Medicine Technology', 'B9C01Q': 'BACHELOR OF HEALTH SCIENCES (CHIROPRACTIC)', 'B9CM1Q': 'BACHELOR OF HEALTH SCIENCES (COMP MEDICINE)', 'B9P01Q': 'BACHELOR OF HEALTH SCIENCES (PODIATRY)', 'B9S14Q': 'BCom in Sport Management', 'B9SE1Q': 'BHS (Sport and Exercise Science)', 'B9E01Q': 'BHS in Emergency Medical Care', 'B9B01Q': 'BHS in Medical Laboratory Sciences', 'B9S15Q': 'Bachelor of Biokinetics', 'B9ENV1': 'Bachelor of Environmental Health', 'B9N02Q': 'Bachelor of Nursing', 'D9S01Q': 'Diploma in Sport Management'};
        const humanities = {'B7EX2Q': 'BA EXTENDED IN DEVELOPMENT STUDIES', 'B7EX3Q': 'BA EXTENDED IN LINGUISTICS', 'B7EX4Q': 'BA EXTENDED IN LINGUISTICS & LANGUAGE', 'B7EX5Q': 'BA EXTENDED IN STRATEGIC COMMUNICATIONS', 'B7015Q': 'BA IN COMMUNITY DEVELOPMENT & LEADERSHIP', 'B7026Q': 'BA WITH SPECIALISATION IN LANGUAGE PRACTICE', 'B7025Q': 'BACHELOR OF SOCIAL WORK', 'D7002Q': 'DIPLOMA IN PUBLIC RELATIONS & COMMUNICATION', 'D7EX2Q': 'DIPLOMA IN PUBLIC RELATIONS & COMMUNICATION'};
        const law = {'B4A01Q': 'BA in Law', 'B4C01Q': 'BCom in Law', 'B4L03Q': 'LLB IN LAW'};

        var key;
        var option;

        var selectElement = document.getElementById(course);
        
        if ( faculty === "ART, DESIGN AND ARCHITECTURE") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (key in arts) {
                option = document.createElement('option');
                option.value = arts[key];
                option.textContent = arts[arts[key]];
                selectElement.appendChild(option);
            }
        }else if ( faculty === "COLLEGE OF BUSINESS &ECONOMICS") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (key in collegeBusines) {
                option = document.createElement('option');
                option.value = collegeBusines[key];
                option.textContent = collegeBusines[key];
                selectElement.appendChild(option);
            }
        }else if ( faculty === "EDUCATION") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (key in education) {
                option = document.createElement('option');
                option.value = education[key];
                option.textContent = education[key];
                selectElement.appendChild(option);
            }
        }else if ( faculty === "ENGINEERING&BUILT ENVIRONMENT") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (key in engineering) {
                option = document.createElement('option');
                option.value = engineering[key];
                option.textContent = engineering[key];
                selectElement.appendChild(option);
            }
        }else if ( faculty === "FACULTY OF SCIENCE") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (key in science) {
                option = document.createElement('option');
                option.value = science[key];
                option.textContent = science[key];
                selectElement.appendChild(option);
            }
        }else if ( faculty === "HUMANITIES") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (key in humanities) {
                option = document.createElement('option');
                option.value = humanities[key];
                option.textContent = humanities[key];
                selectElement.appendChild(option);
            }
        }else if ( faculty === "LAW") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (key in law) {
                option = document.createElement('option');
                option.value = law[key];
                option.textContent = law[key];
                selectElement.appendChild(option);
            }
        }else if ( faculty === "HEALTH SCIENCES") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (key in health) {
                option = document.createElement('option');
                option.value = health[key];
                option.textContent = health[key];
                selectElement.appendChild(option);
            }
        }
    }

    function uwc(faculty, course){
        
        var arts = ['Occasional - Non Degree', 'BTh', 'BA', 'BLIS Library and Information Studies'];
        var commu = ['BSc Sport & Exercise Science', 'BA Sport Recreation\xa0\xa0and Exercise Science', 'BSc Occupational Therapy', 'BSc Physiotherapy', 'BSc Dietetics', 'B Nursing (N)', 'BCM Complementary Medicine: Phytotherapy', 'BCM Complementary Medicine: Naturopathy', 'BCM Complementary Medicine: Chinese Medicine and Acupuncture', 'BCM Complementary Medicine: Unani Tibb', 'B. Social Work', 'B. Community Development'];
        var denstist = ['Occasional - Non Degree', 'Study Abroad', 'Exchange Student', 'BDS', 'BOral Health'];
        var eco = ['BCom\xa0\xa0(N)', 'BAdmin', 'BCom Accounting (Full-Time) 3 Year', 'BCom (IS)', 'Continuous Education Programme', 'Exchange Student', 'BCom\xa0\xa0Financial Accounting', 'Higher Certificate in Economic Development', 'Advanced Diploma in Accounting', 'Advanced Diploma in Public Administration', 'Advanced Diploma in Public Administration (F)', 'Advanced Diploma in Management (Full-Time)'];
        var law = ['Exchange Student', 'LLB\xa0\xa04 Year (Full Time)', 'BCom Law (Full-Time)', 'BA Law (Full-Time)', 'Advanced Diploma in Labour Law'];
        var natural =['BSc Biotechnology', 'BSc Applied Geology', 'BSc Biodiversity & Conservation Biology', 'BSc Chemical Sciences', 'BSc Computer Science', 'BSc Mathematics & Statistical Science', 'BSc Medical Bioscience', 'BSc Physical Science', 'BPharm (N)', 'BSc Environmental & Water Science'];
        var edu = ['BEd Acc(FET) & EMS & Maths(SP)', 'BEd Languages(FET) & Life Orientation(SP)', 'BEd Languages(FET) & Maths(SP)', '! BEd Languages(FET) & Social Sciences(SP)', 'BEd MLIT(FET) &\xa0\xa0Maths & Nat Sciences(SP)', 'BEd (Foundation Phase Teaching)'];

        var selectElement = document.getElementById(course);
        var option;
        var i;

        if ( faculty === "ART") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (i = 0; i < arts.length; i++) {
                option = document.createElement('option');
                option.value = arts[i];
                option.textContent = arts[i];
                selectElement.appendChild(option);
            }
        }
        else if ( faculty === "CHS") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (i = 0; i < commu.length; i++) {
                option = document.createElement('option');
                option.value = commu[i];
                option.textContent = commu[i];
                selectElement.appendChild(option);
            }
        } else if ( faculty === "DEN") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (i = 0; i < denstist.length; i++) {
                option = document.createElement('option');
                option.value = denstist[i];
                option.textContent = denstist[i];
                selectElement.appendChild(option);
            }
        } else if ( faculty === "SCI") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (i = 0; i < natural.length; i++) {
                option = document.createElement('option');
                option.value = natural[i];
                option.textContent = natural[i];
                selectElement.appendChild(option);
            }
        } else if ( faculty === "EDU") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (i = 0; i < edu.length; i++) {
                option = document.createElement('option');
                option.value = edu[i];
                option.textContent = edu[i];
                selectElement.appendChild(option);
            }
        }
        else if ( faculty === "EMS") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (i = 0; i < eco.length; i++) {
                option = document.createElement('option');
                option.value = eco[i];
                option.textContent = eco[i];
                selectElement.appendChild(option);
            }
        } else if ( faculty === "LAW") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (i = 0; i < law.length; i++) {
                option = document.createElement('option');
                option.value = law[i];
                option.textContent = law[i];
                selectElement.appendChild(option);
            }
        }
    }

    function nwu1(campus, course){
        const mahikeng = ["BA IN COMMUNICATION  (1GC H01 1)", "BA IN HUMANITIES WITH ENGLISH  (1GS H10 1)", "BA IN HUMANITIES WITH FRENCH  (1GS H11 1)", "BA IN HUMANITIES WITH GEOGRAPHY  (1GS H08 1)", "BA IN HUMANITIES WITH GEOGRAPHY AND SOCIETY  (1GS H23 1)", "BA IN HUMANITIES WITH HISTORY  (1GS H07 1)", "BA IN HUMANITIES WITH HISTORY AND SOCIETY  (1GS H21 1)", "BA IN HUMANITIES WITH PHILOSOPHY  (1GS H20 1)", "BA IN HUMANITIES WITH PSYCHOLOGY  (1GS H05 1)", "BA IN HUMANITIES WITH PSYCHOLOGY AND SOCIETY  (1GS H22 1)", "BA IN HUMANITIES WITH SETSWANA  (1GS H15 1)", "BA IN HUMANITIES WITH SOCIOLOGY  (1GS H19 1)", "BA IN LANGUAGE AND LITERARY STUDIES  (1GM H16 1)", "BA IN PASTORAL PSYCHOLOGY  (3DC H02 1)", "BA WITH TOURISM MANAGEMENT  (1GB H02 1)", "BACHELOR OF INDIGENOUS KNOWLEDGE SYSTEMS  (2HB K01 1)", "BACHELOR OF NURSING  (8NE K01 1)", "BACHELOR OF SOCIAL WORK  (8EW K01 1)", "BADMIN IN DEVELOPMENT AND MAN WITH LOCAL GOVERNMENT MANAGEME  (1DC H01 1)", "BADMIN WITH HUMAN RESOURCE MANAGEMENT  (5FD H01 1)", "BADMIN WITH ORGANISATIONAL PSYCHOLOGY  (5FD H02 1)", "BCOM IN BUSINESS OPERATIONS WITH LOGISTICS MANAGEMENT  (5FJ H01 1)", "BCOM IN BUSINESS OPERATIONS WITH TRANSPORT ECONOMICS  (5FJ H02 1)", "BCOM IN CHARTERED ACCOUNTANCY  (5DA H01 1)", "BCOM IN ECONOMIC SCIENCES WITH ECONOMETRICS  (5FK H03 1)", "BCOM IN FINANCIAL ACCOUNTANCY  (5DB H01 1)", "BCOM IN HUMAN RESOURCE MANAGEMENT  (5FM H01 1)", "BCOM IN INDUSTRIAL AND ORGANISATIONAL PSYCHOLOGY WITH LRM  (5FN H01 1)", "BCOM IN INFORMATION SYSTEMS  (5GV H01 1)", "BCOM IN LAW  (6DD H01 1)", "BCOM IN MANAGEMENT SCIENCES WITH BUSINESS MANAGEMENT  (5FP H02 1)", "BCOM IN MANAGEMENT SCIENCES WITH COMMUNICATION MANAGEMENT  (5FP H03 1)", "BCOM IN MANAGEMENT SCIENCES WITH MARKETING AND TOURISM MANAG  (5FP H05 1)", "BCOM IN MANAGEMENT SCIENCES WITH MARKETING MANAGEMENT  (5FP H01 1)", "BCOM WITH OPERATIONS RESEARCH  (5FG H03 1)", "BCOM WITH STATISTICS  (5FG H02 1)", "BED IN FOUNDATION PHASE  (4FA J01 1)", "BED IN SNR & FET WITH ACCOUNTING FOR EDUCATION  (4FE J12 1)", "BED IN SNR & FET WITH BUSINESS STUDIES FOR EDUCATION  (4FE J11 1)", "BED IN SNR & FET WITH ECONOMICS FOR EDUCATION  (4FE J05 1)", "BED IN SNR & FET WITH ENGLISH FOR EDUCATION  (4FE J04 1)", "BED IN SNR & FET WITH GEOGRAPHY FOR EDUCATION  (4FE J07 1)", "BED IN SNR & FET WITH HISTORY FOR EDUCATION  (4FE J06 1)", "BED IN SNR & FET WITH LIFE SCIENCE FOR EDUCATION  (4FE J02 1)", "BED IN SNR & FET WITH MATHEMATICS FOR EDUCATION  (4FE J14 1)", "BED IN SNR & FET WITH PHYSICAL SCIENCE FOR EDUCATION  (4FE J10 1)", "BED IN SNR & FET WITH SETSWANA (M) FOR EDUCATION  (4FE J15 1)", "BHSC WITH SPORT COACHING AND HUMAN MOVEMENT SCIENCES  (8DJ H03 1)", "BSC IN AGRICULTURE WITH AGRICULTURAL ECONOMICS  (2FD K01 1)", "BSC IN AGRICULTURE WITH AGRONOMY ND HORTICULTURE  (2FD K04 1)", "BSC IN AGRICULTURE WITH ANIMAL HEALTH  (2FD K07 1)", "BSC IN AGRICULTURE WITH ANIMAL SCIENCE  (2FD K03 1)", "BSC IN BIOLOGICAL SCIENCES WITH BOTANY & BIOCHEMISTRY  (2DK H02 1)", "BSC IN BIOLOGICAL SCIENCES WITH MICROBIOLOGY &  BOTANY  (2DK H10 1)", "BSC IN BIOLOGICAL SCIENCES WITH MICROBIOLOGY & BIOCHEM  (2DK H11 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH BOTANY & CHEMISTRY  (2DJ H03 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH CHEMISTRY &  MICROBIOLOGY  (2DJ H10 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH CHEMISTRY & GEOGRAPHY  (2DJ H18 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH GEOGRAPHY & BOTANY  (2DJ H06 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH GEOGRAPHY & COMP SCIENCE  (2DJ H14 1)", "BSC IN MATHEMATICAL SCIENCE WITH APPLIED MATH AND MATH  (2FG H03 1)", "BSC WITH APPLIED MATHEMATICS AND CHEMISTRY  (2FF H13 1)", "BSC WITH BIOCHEMISTRY AND CHEMISTRY  (2FF H06 1)", "BSC WITH CHEMISTRY AND COMPUTER SCIENCE  (2FF H31 1)", "BSC WITH CHEMISTRY AND MATHEMATICS  (2FF H11 1)", "BSC WITH CHEMISTRY AND PHYSICS  (2FF H05 1)", "BSC WITH COMPUTER SCIENCE AND ELECTRONICS  (2FF H17 1)", "BSC WITH COMPUTER SCIENCE AND MATHEMATICS  (2FF H09 1)", "BSC WITH ELECTRONICS AND PHYSICS  (2FF H20 1)", "BSC WITH PHYSICS AND APPLIED MATHEMATICS  (2FF H24 1)", "BSC WITH PHYSICS AND COMPUTER SCIENCE  (2FF H25 1)", "BSC WITH PHYSICS AND MATHEMATICS  (2FF H23 1)", "BSOCSCI WITH DEVELOPMENT STUDIES  (1GG H30 1)", "BSOCSCI WITH ECONOMICS  (1GG H31 1)", "BSOCSCI WITH GEOGRAPHY  (1GG H32 1)", "BSOCSCI WITH HISTORY  (1GG H33 1)", "BSOCSCI WITH POLITICAL STUDIES AND INTERNATIONAL RELATIONS  (1GG H28 1)", "BSOCSCI WITH POPULATION STUDIES  (1GG H34 1)", "BSOCSCI WITH PSYCHOLOGY  (1GG H38 1)", "BSOCSCI WITH PSYCHOLOGY AND THE SOCIAL SCIENCES  (1GG H35 1)", "BSOCSCI WITH SOCIOLOGY  (1GG H37 1)", "BTH WITH CHRISTIAN MINISTRY  (3DF H01 1)", "DIPLOMA IN ANIMAL HEALTH  (2DY B01 1)", "DIPLOMA IN ANIMAL SCIENCE  (2FH B01 1)", "DIPLOMA IN COACHING SCIENCE  (8EN A02 1)", "DIPLOMA IN PLANT SCIENCE WITH CROP PRODUCTION  (2FJ B01 1)", "EXT BADMIN IN DEVELOP AND MANG WITH LOCAL GOVERNMENT MANAG  (1XC H01 1)", "EXT BADMIN WITH HUMAN RESOURCE MANAGEMENT  (5XD H01 1)", "EXT BADMIN WITH ORGANISATIONAL PSYCHOLOGY  (5XD H02 1)", "EXT BCOM IN BUSINESS OPERATIONS WITH LOGISTICS MANAGEMENT  (5XJ H01 1)", "EXT BCOM IN BUSINESS OPERATIONS WITH TRANSPORT ECONOMICS  (5XJ H02 1)", "EXT BCOM IN CHARTERED ACCOUNTANCY  (5XA H01 1)", "EXT BCOM IN ECONOMIC SCIENCES WITH ECONOMETRICS  (5XK H03 1)", "EXT BCOM IN FINANCIAL ACCOUNTANCY  (5XB H01 1)", "EXT BCOM IN INFORMATION SYSTEMS  (5XV H01 1)", "EXT BCOM IN MANAGEMENT SCIENCES WITH BUSINESS MANAGEMENT  (5XP H02 1)", "EXT BCOM IN MANAGEMENT SCIENCES WITH MARKETING MANAGEMENT  (5XP H01 1)", "EXT BCOM WITH STATISTICS  (5XG H01 1)", "EXT BSC IN  ENVIRONMENTAL SCIENCES WITH CHEMISTRY AND GEOG  (2XJ H18 1)", "EXT BSC IN BIOLOGICAL SCIENCES WITH BOTANY AND BIOCHEMISTRY  (2XK H01 1)", "EXT BSC IN BIOLOGICAL SCIENCES WITH BOTANY AND MICROBIOLOGY  (2XK H02 1)", "EXT BSC IN BIOLOGICAL SCIENCES WITH MICROBIOLOGY AND BIOCHEM  (2XK H11 1)", "EXT BSC IN ENVIRONMENTAL SCIENCES WITH  BOTANY AND CHEMISTRY  (2XJ H03 1)", "EXT BSC IN ENVIRONMENTAL SCIENCES WITH CHEMISTRY &  MICROBIO  (2XJ H10 1)", "EXT BSC IN ENVIRONMENTAL SCIENCES WITH GEOGRAPHY AND BOTANY  (2XJ H06 1)", "EXT BSC IN ENVIRONMENTAL SCIENCES WITH GEOGRAPHY AND COMP SC  (2XJ H14 1)", "EXT BSC IN MATH SCIENCE WITH APPLIED MATH AND MATHEMATICS  (2XG H03 1)", "EXT BSC WITH APPLIED MATHEMATICS AND CHEMISTRY  (2XF H13 1)", "EXT BSC WITH APPLIED MATHEMATICS AND ELECTRONICS  (2XF H14 1)", "EXT BSC WITH APPLIED MATHEMATICS AND PHYSICS  (2XF H24 1)", "EXT BSC WITH BIOCHEMISTRY AND CHEMISTRY  (2XF H06 1)", "EXT BSC WITH CHEMISTRY AND COMPUTER SCIENCE  (2XF H31 1)", "EXT BSC WITH CHEMISTRY AND MATHEMATICS  (2XF H11 1)", "EXT BSC WITH CHEMISTRY AND PHYSICS  (2XF H05 1)", "EXT BSC WITH COMPUTER SCIENCE AND ELECTRONICS  (2XF H17 1)", "EXT BSC WITH COMPUTER SCIENCE AND MATHEMATICS  (2XF H09 1)", "EXT BSC WITH ELECTRONICS AND MATHEMATICS  (2XF H19 1)", "EXT BSC WITH ELECTRONICS AND PHYSICS  (2XF H20 1)", "EXT BSC WITH PHYSICS AND COMPUTER SCIENCE  (2XF H25 1)", "EXT BSC WITH PHYSICS AND MATHEMATICS  (2XF H23 1)", "EXT LLB  (6XA H01 1)", "LLB  (6DE H01 1)", "LLB (ONLY SNR STUDENTS AFTER BA IN LAW)  (6DE H02 1)", "LLB (ONLY SNR STUDENTS AFTER BCOM IN LAW)  (6DE H03 1)"]
        const potchefstroom = ["BA IN ANCIENT LANGUAGES  (3BB H04 1)", "BA IN BEHAVIOURAL SCIENCES WITH PSYCHOLOGY & LRM  (1GR H02 1)", "BA IN BEHAVIOURAL SCIENCES WITH SOCIOLOGY AND PSYCHOLOGY  (1GR H01 1)", "BA IN COMMUNICATION  (1GC H01 1)", "BA IN GRAPHIC DESIGN  (1DN K01 1)", "BA IN GRAPHIC DESIGN WITH COMMUNICATION  (1DN K02 1)", "BA IN HUMANITIES WITH AFRIKAANS AND DUTCH  (1GS H09 1)", "BA IN HUMANITIES WITH ENGLISH  (1GS H10 1)", "BA IN HUMANITIES WITH FRENCH  (1GS H11 1)", "BA IN HUMANITIES WITH GEOGRAPHY  (1GS H08 1)", "BA IN HUMANITIES WITH GERMAN  (1GS H12 1)", "BA IN HUMANITIES WITH HISTORY  (1GS H07 1)", "BA IN HUMANITIES WITH HISTORY OF ART  (1GS H13 1)", "BA IN HUMANITIES WITH LATIN  (1GS H14 1)", "BA IN HUMANITIES WITH PHILOSOPHY  (1GS H20 1)", "BA IN HUMANITIES WITH POLITICS  (1GS H17 1)", "BA IN HUMANITIES WITH PSYCHOLOGY  (1GS H05 1)", "BA IN HUMANITIES WITH SETSWANA  (1GS H15 1)", "BA IN HUMANITIES WITH SOCIAL ANTHROPOLOGY  (1GS H18 1)", "BA IN HUMANITIES WITH SOCIOLOGY  (1GS H19 1)", "BA IN HUMANITIES WITH SOSIAL SCIENCES  (1GS H03 1)", "BA IN LANGUAGE AND LITERARY STUDIES  (1GM H16 1)", "BA IN LANGUAGE TECHNOLOGY  (1GU H01 1)", "BA IN LAW WITH INDUSTRIAL PSYCHOLOGY  (6DC H03 1)", "BA IN LAW WITH POLITICS  (6DC H02 1)", "BA IN LAW WITH PSYCHOLOGY  (6DC H06 1)", "BA IN MUSIC WITH MUSIC AND SOCIETY  (1GD H01 1)", "BA IN PUBLIC GOV WITH MUNICIPAL MANAGEMENT AND LEADERSHIP  (1GE H03 1)", "BA IN PUBLIC GOV WITH POLITICS AND PUBLIC ADMINISTRATION  (1GE H02 1)", "BA IN PUBLIC GOV WITH PUBLIC ADMIN AND GEOGRAPHY  (1GE H05 1)", "BA IN PUBLIC GOV WITH PUBLIC ADMIN AND LABOUR RELATIONS MANG  (1GE H06 1)", "BA IN PUBLIC GOV WITH PUBLIC ADMIN AND SOCIAL STUDIES  (1GE H04 1)", "BA IN PUBLIC GOV WITH PUBLIC ADMINISTRATION  (1GE H01 1)", "BA WITH INDUSTRIAL AND ORGANISATIONAL PSYCHOLOGY AND LRM  (1GB H03 1)", "BA WITH PSYCHOLOGY & GEOGRAPHY AND ENVIRONMENTAL MANAGEMENT  (1GB H10 1)", "BA WITH PSYCHOLOGY AND TOURISM MANAGEMENT  (1GB H11 1)", "BA WITH SOCIOLOGY AND GEOGRAPHY  (1GB H05 1)", "BA WITH SOCIOLOGY AND LABOUR RELATIONS MANAGEMENT  (1GB H07 1)", "BACHELOR OF CONSUMER STUDIES  (8EF H01 1)", "BACHELOR OF DIVINITY  (3BC K01 1)", "BACHELOR OF NURSING  (8NE K01 1)", "BACHELOR OF SOCIAL WORK  (8EW K01 1)", "BCOM IN CHARTERED ACCOUNTANCY  (5DA H01 1)", "BCOM IN ECONOMIC SCIENCES WITH AGRI ECONOMICS & RISK MAN  (5FK H04 1)", "BCOM IN ECONOMIC SCIENCES WITH ECONOMICS AND INFORMATICS  (5FK H02 1)", "BCOM IN ECONOMIC SCIENCES WITH ECONOMICS AND RISK MANAGEMENT  (5FK H05 1)", "BCOM IN ECONOMIC SCIENCES WITH INTERNATIONAL TRADE  (5FK H01 1)", "BCOM IN FINANCIAL ACCOUNTANCY  (5DB H01 1)", "BCOM IN FORENSIC ACCOUNTANCY  (5DD H01 1)", "BCOM IN HUMAN RESOURCE MANAGEMENT  (5FM H01 1)", "BCOM IN INDUSTRIAL AND ORGANISATIONAL PSYCHOLOGY WITH LRM  (5FN H01 1)", "BCOM IN LAW  (6DD H01 1)", "BCOM IN MANAGEMENT ACCOUNTANCY  (5DC H01 1)", "BCOM IN MANAGEMENT SCIENCES WITH BUSINESS MANAGEMENT  (5FP H02 1)", "BCOM IN MANAGEMENT SCIENCES WITH COMMUNICATION MANAGEMENT  (5FP H03 1)", "BCOM IN MANAGEMENT SCIENCES WITH MARKETING AND TOURISM MANAG  (5FP H05 1)", "BCOM IN MANAGEMENT SCIENCES WITH MARKETING MANAGEMENT  (5FP H01 1)", "BCOM IN MANAGEMENT SCIENCES WITH TOURISM MAN AND RECREATION  (5FP H04 1)", "BCOM IN MANAGEMENT SCIENCES WITH TOURISM MANAGEMENT  (5FP H06 1)", "BCONSCI IN FASHION RETAIL MANAGEMENT WITH FASHION COMMUNICAT  (8DT K02 1)", "BCONSCI IN FASHION RETAIL MANAGEMENT WITH FASHION SUPPLY  (8DT K01 1)", "BCONSCI IN FOOD PRODUCT MANAGEMENT WITH FOOD COMMUNICATION  (8DS K02 1)", "BCONSCI IN FOOD PRODUCT MANAGEMENT WITH FOOD SUPPLY  (8DS K01 1)", "BED IN FOUNDATION PHASE  (4FA J01 1)", "BED IN INTERMEDIATE PHASE WITH LIFE SKILLS & SOCIAL SC  (4FC J02 1)", "BED IN INTERMEDIATE PHASE WITH MATHS, SCIENCE & TECHNOLOGY  (4FC J01 1)", "BED IN SNR & FET WITH ACCOUNTING FOR EDUCATION  (4FE J12 1)", "BED IN SNR & FET WITH AFRIKAANS FOR EDUCATION  (4FE J01 1)", "BED IN SNR & FET WITH ART FOR EDUCATION  (4FE J09 1)", "BED IN SNR & FET WITH BUSINESS STUDIES FOR EDUCATION  (4FE J11 1)", "BED IN SNR & FET WITH CIVIL TECHNOLOGY FOR EDUCATION  (4FE J18 1)", "BED IN SNR & FET WITH COMPUTER APPLICATIONS TECH FOR EDUCAT  (4FE J13 1)", "BED IN SNR & FET WITH ECONOMICS FOR EDUCATION  (4FE J05 1)", "BED IN SNR & FET WITH ELECTRICAL TECHNOLOGY FOR EDUCATION  (4FE J19 1)", "BED IN SNR & FET WITH ENGINEERING GRAPHICS AND DESIGN FOR ED  (4FE J16 1)", "BED IN SNR & FET WITH ENGLISH FOR EDUCATION  (4FE J04 1)", "BED IN SNR & FET WITH GEOGRAPHY FOR EDUCATION  (4FE J07 1)", "BED IN SNR & FET WITH HISTORY FOR EDUCATION  (4FE J06 1)", "BED IN SNR & FET WITH INFORMATION TECHNOLOGY EDUCATION  (4FE J03 1)", "BED IN SNR & FET WITH LIFE ORIENTATION FOR EDUCATION  (4FE J08 1)", "BED IN SNR & FET WITH LIFE SCIENCE FOR EDUCATION  (4FE J02 1)", "BED IN SNR & FET WITH MATHEMATICS FOR EDUCATION  (4FE J14 1)", "BED IN SNR & FET WITH MECHANICAL TECHNOLOGY FOR EDUCATION  (4FE J17 1)", "BED IN SNR & FET WITH PHYSICAL SCIENCE FOR EDUCATION  (4FE J10 1)", "BED IN SNR & FET WITH SESOTHO (M) FOR EDUCATION  (4FE J21 1)", "BED IN SNR & FET WITH SETSWANA (M) FOR EDUCATION  (4FE J15 1)", "BENG IN CHEMICAL ENGINEERING  (7CG K03 1)", "BENG IN COMPUTER AND ELECTRONIC ENGINEERING  (7CH K01 1)", "BENG IN ELECTRICAL & ELECTRONIC ENGINEERING  (7CN K01 1)", "BENG IN ELECTRO-MECHANICAL ENGINEERING  (7CL K01 1)", "BENG IN INDUSTRIAL ENGINEERING  (7CK K01 1)", "BENG IN MECHANICAL ENGINEERING  (7CJ K01 1)", "BENG IN MECHATRONIC ENGINEERING  (7CR K01 1)", "BHRD IN HUMAN RESOURCE DEVELOPMENT  (5FQ H01 1)", "BHSC IN BIOKINETICS  (8DR K01 1)", "BHSC IN OCCUPATIONAL HYGIENE  (8EB K01 1)", "BHSC WITH PHYSIOLOGY AND BIOCHEMISTRY  (8DJ H01 1)", "BHSC WITH PHYSIOLOGY AND PSYCHOLOGY  (8DJ H02 1)", "BHSC WITH RECREATION SCIENCE & PSYCHOLOGY  (8DJ H05 1)", "BHSC WITH RECREATION SCIENCE & TOURISM MANAGEMENT  (8DJ H06 1)", "BHSC WITH SPORT AND RECREATION ADMINISTRATION  (8DJ H07 1)", "BHSC WITH SPORT COACHING AND HUMAN MOVEMENT SCIENCES  (8DJ H03 1)", "BMUS IN MUSIC  (1GK K01 1)", "BPHARM IN PHARMACY  (8EK K01 1)", "BPHIL WITH PHILOSOPHY, POLITICS AND ECONOMICS (PPE)  (1GF H08 1)", "BSC IN ACTUARIAL SCIENCE  (2FQ H01 1)", "BSC IN AGRICULTURE WITH AGRONOMY AND AGRICULTURAL ECONOMICS  (2FD K09 1)", "BSC IN AGRICULTURE WITH AGRONOMY AND SOIL SCIENCE  (2FD K08 1)", "BSC IN BIOLOGICAL SCIENCES WITH BOTANY & BIOCHEMISTRY  (2DK H02 1)", "BSC IN BIOLOGICAL SCIENCES WITH CHEMISTRY & PHYSIOLOGY  (2DK H06 1)", "BSC IN BIOLOGICAL SCIENCES WITH MICROBIOLOGY &  BOTANY  (2DK H10 1)", "BSC IN BIOLOGICAL SCIENCES WITH MICROBIOLOGY & BIOCHEM  (2DK H11 1)", "BSC IN BIOLOGICAL SCIENCES WITH MICROBIOLOGY & PHYSIOLOGY  (2DK H04 1)", "BSC IN BIOLOGICAL SCIENCES WITH ZOOLOGY &  BIOCHEMISTRY  (2DK H07 1)", "BSC IN BIOLOGICAL SCIENCES WITH ZOOLOGY &  BOTANY  (2DK H09 1)", "BSC IN BIOLOGICAL SCIENCES WITH ZOOLOGY & MICROBIOLOGY  (2DK H08 1)", "BSC IN BIOLOGICAL SCIENCES WITH ZOOLOGY & PHYSIOLOGY  (2DK H03 1)", "BSC IN BUSINESS ANALYTICS  (2FR H01 1)", "BSC IN DIETETICS  (8EL K01 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH BOTANY & CHEMISTRY  (2DJ H03 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH CHEMISTRY &  MICROBIOLOGY  (2DJ H10 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH GEOGRAPHY & BOTANY  (2DJ H06 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH GEOGRAPHY & COMP SCIENCE  (2DJ H14 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH GEOLOGY & BOTANY  (2DJ H02 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH GEOLOGY & CHEMISTRY  (2DJ H07 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH GEOLOGY & GEOGRAPHY  (2DJ H01 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH GEOLOGY & MICROBIOLOGY  (2DJ H09 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH TOURISM & BOTANY  (2DJ H17 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH TOURISM & GEOGRAPHY  (2DJ H16 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH TOURISM & ZOOLOGY  (2DJ H15 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH ZOOLOGY & CHEMISTRY  (2DJ H04 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH ZOOLOGY & GEOGRAPHY  (2DJ H05 1)", "BSC IN ENVIRONMENTAL SCIENCES WITH ZOOLOGY & GEOLOGY  (2DJ H08 1)", "BSC IN FINANCIAL MATHEMATICS  (2FS H01 1)", "BSC IN INFORMATION TECHNOLOGY  (2DX H01 1)", "BSC IN MATHEMATICAL SCIENCE WITH MATHEMATICS  (2FG H01 1)", "BSC IN MATHEMATICAL SCIENCE WITH STATISTICS AND MATHEMATICS  (2FG H02 1)", "BSC IN QUANTITATIVE RISK MANAGEMENT  (2FT H01 1)", "BSC IN URBAN AND REGIONAL PLANNING  (2FE K01 1)", "BSC WITH APPLIED MATHEMATICS AND CHEMISTRY  (2FF H13 1)", "BSC WITH BIOCHEMISTRY AND CHEMISTRY  (2FF H06 1)", "BSC WITH CHEMISTRY AND MATHEMATICS  (2FF H11 1)", "BSC WITH CHEMISTRY AND PHYSICS  (2FF H05 1)", "BSC WITH COMPUTER SCIENCE AND ECONOMICS  (2FF H28 1)", "BSC WITH COMPUTER SCIENCE AND MATHEMATICS  (2FF H09 1)", "BSC WITH COMPUTER SCIENCE AND STATISTICS  (2FF H26 1)", "BSC WITH GEOGRAPHY AND APPLIED MATHEMATICS  (2FF H30 1)", "BSC WITH MATHEMATICS AND ECONOMY  (2FF H29 1)", "BSC WITH PHYSICS AND APPLIED MATHEMATICS  (2FF H24 1)", "BSC WITH PHYSICS AND COMPUTER SCIENCE  (2FF H25 1)", "BSC WITH PHYSICS AND MATHEMATICS  (2FF H23 1)", "BSOCSCI WITH ECONOMICS  (1GG H31 1)", "BSOCSCI WITH GEOGRAPHY  (1GG H32 1)", "BSOCSCI WITH HISTORY  (1GG H33 1)", "BSOCSCI WITH PSYCHOLOGY AND THE SOCIAL SCIENCES  (1GG H35 1)", "BSOCSCI WITH SOCIAL ANTHROPOLOGY  (1GG H36 1)", "BSOCSCI WITH SOCIOLOGY  (1GG H37 1)", "BTH WITH BIBLE LANGUAGES AND BIBLE TRANSLATION  (3DD H03 1)", "BTH WITH CHRISTIAN MINISTRY  (3DF H01 1)", "BTH WITH PASTORAL COUNSELLING AND PSYCHOLOGY  (3DD H01 1)", "DIPLOMA IN COACHING SCIENCE  (8EN A02 1)", "DIPLOMA IN MUSIC  (1GL B01 1)", "LLB  (6DE H01 1)", "LLB (ONLY SNR STUDENTS AFTER BA IN LAW)  (6DE H02 1)", "LLB (ONLY SNR STUDENTS AFTER BCOM IN LAW)  (6DE H03 1)"]
        const vanderbijlpark = ["BA IN BEHAVIOURAL SCIENCES WITH PSYCHOLOGY & LRM  (1GR H02 1)", "BA IN BEHAVIOURAL SCIENCES WITH SOCIOLOGY AND PSYCHOLOGY  (1GR H01 1)", "BA IN COMMUNICATION  (1GC H01 1)", "BA IN HUMANITIES WITH AFRIKAANS AND DUTCH  (1GS H09 1)", "BA IN HUMANITIES WITH ENGLISH  (1GS H10 1)", "BA IN HUMANITIES WITH FRENCH  (1GS H11 1)", "BA IN HUMANITIES WITH GEOGRAPHY  (1GS H08 1)", "BA IN HUMANITIES WITH GEOGRAPHY AND SOCIETY  (1GS H23 1)", "BA IN HUMANITIES WITH HISTORY  (1GS H07 1)", "BA IN HUMANITIES WITH HISTORY AND SOCIETY  (1GS H21 1)", "BA IN HUMANITIES WITH POLITICS  (1GS H17 1)", "BA IN HUMANITIES WITH POLITICS AND SOCIETY  (1GS H24 1)", "BA IN HUMANITIES WITH PSYCHOLOGY  (1GS H05 1)", "BA IN HUMANITIES WITH PSYCHOLOGY AND SOCIETY  (1GS H22 1)", "BA IN HUMANITIES WITH SESOTHO  (1GS H16 1)", "BA IN HUMANITIES WITH SOCIOLOGY  (1GS H19 1)", "BA IN HUMANITIES WITH SOSIAL SCIENCES  (1GS H03 1)", "BA IN LANG & LIT STUDIES WITH LANGUAGE PRACTICE  (1GM H01 1)", "BA IN LANG & LIT STUDIES WITH LANGUAGE PRACTICE AND COMM  (1GM H02 1)", "BA IN LANG & LIT STUDIES WITH LANGUAGES  (1GM H10 1)", "BA IN LAW WITH INDUSTRIAL PSYCHOLOGY  (6DC H03 1)", "BA IN LAW WITH POLITICS  (6DC H02 1)", "BA IN LAW WITH PSYCHOLOGY  (6DC H06 1)", "BA IN PASTORAL PSYCHOLOGY  (3DC H02 1)", "BA IN PUBLIC GOV WITH POLITICS AND PUBLIC ADMINISTRATION  (1GE H02 1)", "BA IN PUBLIC GOV WITH PUBLIC ADMIN AND GEOGRAPHY  (1GE H05 1)", "BA IN PUBLIC GOV WITH PUBLIC ADMIN AND LABOUR RELATIONS MANG  (1GE H06 1)", "BA IN PUBLIC GOV WITH PUBLIC ADMIN AND SOCIAL STUDIES  (1GE H04 1)", "BA IN PUBLIC GOV WITH PUBLIC ADMINISTRATION  (1GE H01 1)", "BA WITH INDUSTRIAL AND ORGANISATIONAL PSYCHOLOGY AND LRM  (1GB H03 1)", "BACHELOR OF SOCIAL WORK  (8EW K01 1)", "BCOM IN ACCOUNTING  (5FH H01 1)", "BCOM IN BUSINESS OPERATIONS WITH LOGISTICS MANAGEMENT  (5FJ H01 1)", "BCOM IN BUSINESS OPERATIONS WITH TRANSPORT ECONOMICS  (5FJ H02 1)", "BCOM IN CHARTERED ACCOUNTANCY  (5DA H01 1)", "BCOM IN ECONOMIC SCIENCES WITH ECONOMICS AND INFORMATICS  (5FK H02 1)", "BCOM IN ECONOMIC SCIENCES WITH ECONOMICS AND RISK MANAGEMENT  (5FK H05 1)", "BCOM IN ECONOMIC SCIENCES WITH INTERNATIONAL TRADE  (5FK H01 1)", "BCOM IN FINANCIAL ACCOUNTANCY  (5DB H01 1)", "BCOM IN HUMAN RESOURCE MANAGEMENT  (5FM H01 1)", "BCOM IN INDUSTRIAL AND ORGANISATIONAL PSYCHOLOGY WITH LRM  (5FN H01 1)", "BCOM IN LAW  (6DD H01 1)", "BCOM IN MANAGEMENT ACCOUNTANCY  (5DC H01 1)", "BCOM IN MANAGEMENT SCIENCES WITH BUSINESS MANAGEMENT  (5FP H02 1)", "BCOM IN MANAGEMENT SCIENCES WITH COMMUNICATION MANAGEMENT  (5FP H03 1)", "BCOM IN MANAGEMENT SCIENCES WITH MARKETING MANAGEMENT  (5FP H01 1)", "BCOM IN MANAGEMENT SCIENCES WITH SAFETY MANAGEMENT  (5FP H08 1)", "BCOM IN MANAGEMENT SCIENCES WITH SPORT BUSINESS MANAGEMENT  (5FP H07 1)", "BED IN FOUNDATION PHASE  (4FA J01 1)", "BED IN INTERMEDIATE PHASE WITH LIFE SKILLS & SOCIAL SC  (4FC J02 1)", "BED IN INTERMEDIATE PHASE WITH MATHS, SCIENCE & TECHNOLOGY  (4FC J01 1)", "BED IN SNR & FET WITH ACCOUNTING FOR EDUCATION  (4FE J12 1)", "BED IN SNR & FET WITH AFRIKAANS FOR EDUCATION  (4FE J01 1)", "BED IN SNR & FET WITH BUSINESS STUDIES FOR EDUCATION  (4FE J11 1)", "BED IN SNR & FET WITH CIVIL TECHNOLOGY FOR EDUCATION  (4FE J18 1)", "BED IN SNR & FET WITH COMPUTER APPLICATIONS TECH FOR EDUCAT  (4FE J13 1)", "BED IN SNR & FET WITH ECONOMICS FOR EDUCATION  (4FE J05 1)", "BED IN SNR & FET WITH ELECTRICAL TECHNOLOGY FOR EDUCATION  (4FE J19 1)", "BED IN SNR & FET WITH ENGINEERING GRAPHICS AND DESIGN FOR ED  (4FE J16 1)", "BED IN SNR & FET WITH ENGLISH FOR EDUCATION  (4FE J04 1)", "BED IN SNR & FET WITH GEOGRAPHY FOR EDUCATION  (4FE J07 1)", "BED IN SNR & FET WITH HISTORY FOR EDUCATION  (4FE J06 1)", "BED IN SNR & FET WITH LIFE ORIENTATION FOR EDUCATION  (4FE J08 1)", "BED IN SNR & FET WITH LIFE SCIENCE FOR EDUCATION  (4FE J02 1)", "BED IN SNR & FET WITH MATHEMATICAL LITERACY FOR EDUCATION  (4FE J20 1)", "BED IN SNR & FET WITH MATHEMATICS FOR EDUCATION  (4FE J14 1)", "BED IN SNR & FET WITH MECHANICAL TECHNOLOGY FOR EDUCATION  (4FE J17 1)", "BED IN SNR & FET WITH PHYSICAL SCIENCE FOR EDUCATION  (4FE J10 1)", "BED IN SNR & FET WITH SESOTHO (M) FOR EDUCATION  (4FE J21 1)", "BSC IN BUSINESS ANALYTICS  (2FR H01 1)", "BSC IN FINANCIAL MATHEMATICS  (2FS H01 1)", "BSC IN INFORMATION TECHNOLOGY  (2DX H01 1)", "BSC IN MATHEMATICAL SCIENCE WITH STATISTICS AND MATHEMATICS  (2FG H02 1)", "BSC IN QUANTITATIVE RISK MANAGEMENT  (2FT H01 1)", "BSC WITH COMPUTER SCIENCE AND ECONOMICS  (2FF H28 1)", "BSC WITH COMPUTER SCIENCE AND MATHEMATICS  (2FF H09 1)", "BSC WITH COMPUTER SCIENCE AND STATISTICS  (2FF H26 1)", "BSC WITH MATHEMATICS AND ECONOMY  (2FF H29 1)", "BSOCSCI WITH ECONOMICS  (1GG H31 1)", "BSOCSCI WITH GEOGRAPHY  (1GG H32 1)", "BSOCSCI WITH HISTORY  (1GG H33 1)", "BSOCSCI WITH PSYCHOLOGY AND THE SOCIAL SCIENCES  (1GG H35 1)", "BSOCSCI WITH SOCIAL ANTHROPOLOGY  (1GG H36 1)", "BSOCSCI WITH SOCIOLOGY  (1GG H37 1)", "EXT BCOM IN BUSINESS OPERATIONS WITH LOGISTICS MANAGEMENT  (5XJ H01 1)", "EXT BCOM IN BUSINESS OPERATIONS WITH TRANSPORT ECONOMICS  (5XJ H02 1)", "EXT BCOM IN CHARTERED ACCOUNTANCY  (5XA H01 1)", "EXT BCOM IN ES WITH ECONOMICS AND RISK MANAGEMENT  (5XK H05 1)", "EXT BCOM IN ES WITH INTERNATIONAL TRADE  (5XK H01 1)", "EXT BCOM IN FINANCIAL ACCOUNTANCY  (5XB H01 1)", "EXT BCOM IN MANAGEMENT SCIENCES WITH MARKETING MANAGEMENT  (5XP H01 1)", "EXT BSC IN BUSINESS ANALYTICS  (2XR H01 1)", "EXT BSC IN FINANCIAL MATHEMATICS  (2XS H01 1)", "EXT BSC IN INFORMATION TECHNOLOGY  (2XX H01 1)", "EXT BSC IN QUANTITATIVE RISK MANAGEMENT  (2XT H01 1)"]
        

        var selectElement = document.getElementById(course);
        var option;
        var i;

        if ( campus === "vanderbijlpark") {
            selectElement.innerHTML = `
            <option value="" selected="" disabled>select an option</option>
            `
            for (i = 0; i < vanderbijlpark.length; i++) {
                option = document.createElement('option');
                option.value = vanderbijlpark[i];
                option.textContent = vanderbijlpark[i];
                selectElement.appendChild(option);
            }
        } else if( campus === "potchefstroom" ) {
            selectElement.innerHTML = `
            <option value="" selected disabled>select an option</option>
            `
            for (i = 0; i < potchefstroom.length; i++) {
                option = document.createElement('option');
                option.value = potchefstroom[i];
                option.textContent = potchefstroom[i];
                selectElement.appendChild(option);
            }
        } else if( campus === "mahikeng" ) {
            selectElement.innerHTML = `
            <option value="" selected disabled>select an option</option>
            `
            for (i = 0; i < mahikeng.length; i++) {
                option = document.createElement('option');
                option.value = mahikeng[i];
                option.textContent = mahikeng[i];
                selectElement.appendChild(option);
            }
        }

    }

  return (
    <div>
        <Navbar />
        <main>
        <section className='features' style={{maxWidth: '800px', margin: 'auto'}}>
        <div>
			<h1 style={{ textAlign: "center", marginBottom: '25px', fontStyle: 'bold'}} >Select the courses you would like to apply for in each university</h1>
            <div className="universities">
            <form method="post" enctype="multipart/form-data" autoComplete="false">
                <div className="nwu cours" style={{marginBottom: '25px'}}>
                    <h3 style={{ textAlign: "center", textDecorationStyle: "double" }}>For University of North West</h3>
                    <div className="course">
                        <h4>Campus option 1</h4>
                        <select className="field" id="nwu_campus1" name="nwu_campus1" onChange={(e)=>{ setNwu_campus1(e.target.value); nwu1(e.target.value, "nwu_course1")}} >
                            <option value="" selected disabled>select an option</option>
                            <option value="mahikeng">Mahikeng</option>
                            <option value="potchefstroom">Potchefstroom</option>
                            <option value="vanderbijlpark">Vanderbijlpark</option>
                        </select>
                        <input className="field" type="text" list="nwu_course1" name="nwu_course1" value={nwu_course1} onChange={(e)=>{setNwu_course1(e.target.value)}} placeholder="type or select for a course"/>
                        <datalist id="nwu_course1">
                            <option value="" selected="" disabled>select an option</option>
                        </datalist>
                    </div>
                    <div className="course">
                        <h4>Campus option 2</h4>
                        <select className="field" id="nwu_campus2" name="nwu_campus2" onChange={(e)=>{ setNwu_campus2(e.target.value); nwu1(e.target.value, "nwu_course2")}}>
                            <option value="" selected disabled>select an option</option>
                            <option value="mahikeng">Mahikeng</option>
                            <option value="potchefstroom">Potchefstroom</option>
                            <option value="vanderbijlpark">Vanderbijlpark</option>
                        </select>
                        <input className="field" type="text" list="nwu_course2" name="nwu_course2" value={nwu_course2} onChange={(e)=>{setNwu_course2(e.target.value)}} placeholder="type or select for a course"/>
                        <datalist id="nwu_course2">
                            <option value="" selected="" disabled>select an option</option>
                        </datalist>
                    </div>

                </div>
                <div className="uwc cours" style={{marginBottom: '25px'}}>
                    <h3 style={{ textAlign: "center", textDecorationStyle: "double" }} >For University of Western Cape</h3>
                    <div className="course">
                        <h4>Faculty option 1</h4>
                        <select name="uwc_faculty1" id="uwc_faculty1" onChange={(e)=> { uwc(e.target.value, "uwc_course1"); setUwc_faculty1(e.target.value);}} >
                            <option value="" selected disabled>select an option</option>
                            <option value="ART">FACULTY OF ARTS AND HUMANITIES</option>
                            <option value="CHS">FACULTY OF COMMUNITY AND HEALTH SCIENCES</option>
                            <option value="DEN">FACULTY OF DENTISTRY</option>
                            <option value="EDU">FACULTY OF EDUCATION</option>
                            <option value="EMS">FACULTY OF ECONOMIC AND MANAGEMENT SCIENCES</option>
                            <option value="LAW">FACULTY OF LAW</option>
                            <option value="SCI">FACULTY OF NATURAL SCIENCES</option>
                        </select>
                        <input className="field" type="text" list="uwc_course1" name="uwc_course1" value={uwc_course1} onChange={(e)=>{setUwc_course1(e.target.value)}} placeholder="type or select for a course"/>
                        <datalist id="uwc_course1">
                            <option value="" selected="" disabled>select an option</option>
                        </datalist>
                    </div>
                    <div className="course">
                        <h4>faculty option 2</h4>
                        <select name="uwc_faculty2" id="uwc_faculty2" onChange={(e)=> { uwc(e.target.value, "uwc_course2"); setUwc_faculty2(e.target.value);}}>
                            <option value="" selected disabled>select an option</option>
                            <option value="ART">FACULTY OF ARTS AND HUMANITIES</option>
                            <option value="CHS">FACULTY OF COMMUNITY AND HEALTH SCIENCES</option>
                            <option value="DEN">FACULTY OF DENTISTRY</option>
                            <option value="EDU">FACULTY OF EDUCATION</option>
                            <option value="EMS">FACULTY OF ECONOMIC AND MANAGEMENT SCIENCES</option>
                            <option value="LAW">FACULTY OF LAW</option>
                            <option value="SCI">FACULTY OF NATURAL SCIENCES</option>
                        </select>
                        <input className="field" type="text" list="uwc_course2" name="uwc_course2" value={uwc_course2} onChange={(e)=>{setUwc_course2(e.target.value)}} placeholder="type or select for a course"/>
                        <datalist id="uwc_course2">
                            <option value="" selected="" disabled>select an option</option>
                        </datalist>
                    </div>
                </div>
                <div className="uj cours" style={{marginBottom: '25px'}}>
                    <h3 style={{ textAlign: "center", textDecorationStyle: "double" }} >For University of Johannesburg</h3>
                    <div className="course">
                        <h4>Faculty option 1</h4>
                        <select className="field" id="uj_faculty1" name="uj_faculty1" onChange={ (e)=> {uj1(e.target.value, 'uj_course1'); setUj_faculty1(e.target.value);}} >
                            <option value="" selected disabled>select an option</option>
                            <option value="ART, DESIGN AND ARCHITECTURE">ART, DESIGN AND ARCHITECTURE</option>
                            <option value="COLLEGE OF BUSINESS &ECONOMICS">COLLEGE OF BUSINESS &ECONOMICS</option>
                            <option value="EDUCATION">EDUCATION</option>
                            <option value="ENGINEERING&BUILT ENVIRONMENT">ENGINEERING&BUILT ENVIRONMENT</option>
                            <option value="FACULTY OF SCIENCE">FACULTY OF SCIENCE</option>
                            <option value="HUMANITIES">HUMANITIES</option>
                            <option value="LAW">LAW</option>
                        </select>
                        <input className="field" type="text" list="uj_course1" name="uj_course1" value={uj_course1} onChange={(e)=> {setUj_course1(e.target.value)}} placeholder="type or select for a course"/>
                        <datalist id="uj_course1">
                            <option value="" selected="" disabled>select an option</option>
                        </datalist>
                    </div>
                    <div className="course">
                        <h4>Faculty option 2</h4>
                        <select className="field" id="uj_faculty2" name="uj_faculty2" onChange={ (e)=> {uj1(e.target.value, 'uj_course2'); setUj_faculty2(e.target.value);}} >
                            <option value="" selected disabled>select an option</option>
                            <option value="ART, DESIGN AND ARCHITECTURE">ART, DESIGN AND ARCHITECTURE</option>
                            <option value="COLLEGE OF BUSINESS &ECONOMICS">COLLEGE OF BUSINESS &ECONOMICS</option>
                            <option value="EDUCATION">EDUCATION</option>
                            <option value="ENGINEERING&BUILT ENVIRONMENT">ENGINEERING&BUILT ENVIRONMENT</option>
                            <option value="FACULTY OF SCIENCE">FACULTY OF SCIENCE</option>
                            <option value="HEALTH SCIENCES">HEALTH SCIENCES</option>
                            <option value="HUMANITIES">HUMANITIES</option>
                            <option value="LAW">LAW</option>
                        </select>
                        <input className="field" type="text" list="uj_course2" name="uj_course2" value={uj_course2} onChange={(e)=> {setUj_course2(e.target.value)}} placeholder="type or select for a course"/>
                        <datalist id="uj_course2">
                            <option value="" selected="" disabled>select an option</option>
                        </datalist>
                    </div>

                </div>
                <div style={{ display: "flex", justifyContent: "center", alignItems: "center", marginTop: "20px" }}>
                    <button type="submit" name="submit_app" value="SUBMIT" onClick={(e)=>{ handleSubmit(e)}} className="primary">Submit</button>
                </div>
            </form>
            </div>

        </div>
        </section>
        </main>
        <Footer />
    </div>
  )
}

export default Course